### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by colindaven** [gedoardo83/GARFIELD-NGS#1]
Hi,

just ran this through for the first time. 

For usability it would be great to reduce the long double/float to 2 or 3 decimal places. The last 10+ decimal places don't add anything at all, but make the VCF file big and decrease readability dramatically.

Example
`;31_low_true=0.9152115706043856;35_high_true=0.9152115706043856;56_high_true=0.9152115706043856;`

Suggest change to 
`31_low_true=0.91`

cheers

**Comment by gedoardo83** [comment]
Thanks for your suggestion.
I've fixed this in the latest release v.1.01 that is now available on the repository.
Now GARFIELD-NGS scores are reported in output VCF with fixed 3 decimal values.

**Comment by colindaven** [comment]
Nice, cheers
