### ISSUE TITLE
threshold

### ISSUE THREAD

**Issue by maktolun** [gedoardo83/GARFIELD-NGS#3]
Hello,

In the supplementary tables of the paper, threshold values are given as;

ION SNPs 0.320 INDELs 0.139
Illumina SNPs 0.630 INDELs 0.025

In github page;

ION SNPs 0.139 INDELs 0.320 
Illumina SNPs 0.025 INDELs 0.630

Which info is correct?

**Comment by gedoardo83** [comment]
Hi, 

the correct thresholds are those reported on Github. It seems that values for SNPs/InsDel have been inverted in the supplementary tables. Thanks for pointing out this error.

Please note that these thresholds are provided based on analysis of external datasets, processed by external collaborators during their usual sequencing practice, to achieve maximum sensitivity on every-day use data that have not necessarily been processed following our strict pipeline. 
Usually, we suggest using GARFIELD predictions as a ranking value better than as a hard-filter. If you had some true variants dataset from past sequencing experiments performed with the same workflow and analysis pipeline, you would consider optimizing GARFIELD thresholds on your specific data to increase accuracy.
